---

__apache_vhosts_version: "2.4"
__apache_default_vhost_filename: 000-default.conf
__apache_ports_configuration_items:
  - {
    regexp: "^Listen ",
    line: "Listen {{ (apache_listen_ip == '*') | ternary('', apache_listen_ip + ':') }}{{ apache_listen_port }}"
  }
