---

__apache_vhosts_version: "2.2"
__apache_default_vhost_filename: 000-default
__apache_ports_configuration_items:
  - {
    regexp: "^Listen ",
    line: "Listen {{ apache_listen_port }}"
  }
  - {
    regexp: "^#?NameVirtualHost ",
    line: "NameVirtualHost {{ apache_listen_ip }}:{{ apache_listen_port }}"
  }
