---

- name: Configuration d'Apache
  ansible.builtin.lineinfile:
    dest: "{{ __apache_server_root }}/conf/{{ __apache_daemon }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    mode: 0644
  loop: "{{ __apache_ports_configuration_items }}"
  notify: Redémarrer Apache

- name: Vérification de l'existence des certificats
  ansible.builtin.stat:
    path: "{{ item.certificate_file }}"
  register: __apache_ssl_certificates
  loop: "{{ apache_vhosts_ssl }}"
  no_log: "{{ apache_ssl_no_log }}"

- name: Activation des mods Apache
  ansible.builtin.copy:
    dest: "{{ __apache_server_root }}/conf.modules.d/99-ansible-{{ item }}.conf"
    content: |
      LoadModule {{ item }}_module modules/mod_{{ item }}.so
    mode: 0644
  loop: "{{ apache_mods_enabled }}"
  notify: Redémarrer Apache

- name: Désactivation des mods Apache
  ansible.builtin.file:
    path: "{{ __apache_server_root }}/conf.modules.d/99-ansible-{{ item }}.conf"
    state: absent
  loop: "{{ apache_mods_disabled }}"
  notify: Redémarrer Apache

- name: Ajout de la configuration des vhosts
  ansible.builtin.template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ __apache_conf_path }}/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: Redémarrer Apache
  when: apache_create_vhosts | bool

- name: Vérification de l'existence du certificat localhost (pour RHEL 8+)
  ansible.builtin.stat:
    path: /etc/pki/tls/certs/localhost.crt
  register: __localhost_cert
  when: ansible_distribution_major_version | int >= 8

- name: Vérification des certificats httpd (pour RHEL 8+)
  ansible.builtin.command:
    cmd: /usr/libexec/httpd-ssl-gencerts
  when:
    - ansible_distribution_major_version | int >= 8
    - not __localhost_cert.stat.exists
