---

- name: Playbook pour le backend
  hosts: backend
  tasks:
    # On installe PostgreSQL et une librairie Python qui sert à Ansible à interagir avec
    - name: Installation de PostgreSQL et de la librairie psycopg2
      become: true
      ansible.builtin.package:
        name:
          - postgresql-server
          - python3-psycopg2
        state: present

    # Une fois installé, PostgreSQL n'est pas encore prêt à l'emploi : il faut l'initialiser avec le binaire 'initdb'
    # On va utiliser le chemin par défaut
    - name: Initialisation de PostgreSQL
      become: true
      become_user: postgres
      ansible.builtin.command:
        cmd: initdb --pgdata /var/lib/pgsql/data

    # Par défaut, PostgreSQL n'écoute qu'en local : on va modifier la configuration pour écouter sur toutes les interfaces
    - name: Configuration de PostgreSQL pour écouter sur toutes les interfaces
      become: true
      ansible.builtin.lineinfile:
        path: /var/lib/pgsql/data/postgresql.conf
        regexp: '^[# ]*listen_addresses *='
        line: listen_addresses = '*'
      notify: Redémarrage de PostgreSQL

    # Dans l'intérêt de proposer un système le plus sécurisé possible, on va utiliser SCRAM-SHA-256 pour les mots de passe plutôt que MD5 par défaut
    - name: Configuration de PostgreSQL pour utiliser SCRAM-SHA-256 avec les mots de passe
      become: true
      ansible.builtin.lineinfile:
        path: /var/lib/pgsql/data/postgresql.conf
        regexp: '^[# ]*password_encryption *='
        line: password_encryption = 'scram-sha-256'
      notify: Redémarrage de PostgreSQL

    # On va copier un fichier pg_hba.conf personnalisé
    - name: Copie du fichier pg_hba.conf
      become: true
      ansible.builtin.template:
        # Comme on utilise le module 'template', il est optionnel de préciser que le fichier se trouve dans le dossier 'templates'
        src: pg_hba.conf.j2
        dest: /var/lib/pgsql/data/pg_hba.conf
        owner: postgres
        group: postgres
      notify: Redémarrage de PostgreSQL

    # Et une fois que PostgreSQL est configuré, on peut le lancer
    - name: Lancement du service PostgreSQL
      become: true
      ansible.builtin.service:
        name: postgresql
        state: started

    # On va créer un utilisateur dans PostgreSQL
    - name: Création d'un utilisateur PostgreSQL
      # Notez qu'il n'y a pas besoin d'élevation de privilèges ici
      community.postgresql.postgresql_user:
        name: "{{ nom_utilisateur_postgresql }}"
        password: "{{ mot_de_passe_utilisateur_postgresql }}"
        state: present

    # Et on va ensuite créer une base de données dans PostgreSQL, avec notre utilisateur fraîchement créé comme owner
    - name: Création d'une base de données PostgreSQL
      community.postgresql.postgresql_db:
        name: "{{ nom_base_de_donnees_postgresql }}"
        owner: "{{ nom_utilisateur_postgresql }}"
        state: present

    # Enfin, AlmaLinux étant sécurisé par défaut, son firewall ne permet pas de connexion extérieure
    # On va donc utiliser le module 'ansible.posix.firewalld' pour ouvrir le port par défaut de PostgreSQL
    - name: Ouverture du port PostgreSQL sur le firewall
      become: true
      ansible.posix.firewalld:
        service: postgresql
        state: enabled
        immediate: true

  handlers:
    - name: Redémarrage de PostgreSQL
      become: true
      ansible.builtin.systemd:
        name: postgresql
        state: restarted

- name: Play pour le frontend
  hosts: frontend
  tasks:
    - name: Installation de la librairie psycopg2
      become: true
      ansible.builtin.package:
        name: python3-psycopg2
        state: present

    - name: Connexion à la base de données
      community.postgresql.postgresql_info:
        login_host: "{{ hostvars[groups['backend'][0]]['ansible_host'] | default(groups['backend'][0]) }}"
        login_user: "{{ nom_utilisateur_postgresql }}"
        login_password: "{{ mot_de_passe_utilisateur_postgresql }}"
        db: "{{ nom_base_de_donnees_postgresql }}"
