---

__apache_service: apache2
__apache_daemon: apache2
__apache_daemon_path: /usr/sbin/
__apache_server_root: /etc/apache2
__apache_conf_path: /etc/apache2

__apache_packages:
  - apache2
  - apache2-utils

__apache_ports_configuration_items:
  - regexp: "^Listen "
    line: "Listen {{ apache_listen_port }}"
